syntax = "proto3";

package flight.v1;

import "google/protobuf/timestamp.proto";

service FlightService {
  // SearchFlights:
  // - INVALID_ARGUMENT: origin/destination пустые или некорректные
  rpc SearchFlights(SearchFlightsRequest) returns (SearchFlightsResponse);

  // GetFlight:
  // - NOT_FOUND: рейс не найден
  rpc GetFlight(GetFlightRequest) returns (GetFlightResponse);

  // ReserveSeats:
  // - NOT_FOUND: рейс не найден
  // - RESOURCE_EXHAUSTED: недостаточно свободных мест
  // - FAILED_PRECONDITION: рейс не в статусе SCHEDULED
  // - INVALID_ARGUMENT: seat_count <= 0 или некорректный booking_id
  rpc ReserveSeats(ReserveSeatsRequest) returns (ReserveSeatsResponse);

  // ReleaseReservation:
  // - NOT_FOUND: активная резервация не найдена
  // - FAILED_PRECONDITION: резервация уже RELEASED/EXPIRED
  // - INVALID_ARGUMENT: некорректный booking_id
  rpc ReleaseReservation(ReleaseReservationRequest)
      returns (ReleaseReservationResponse);
}

enum FlightStatus {
  FLIGHT_STATUS_UNSPECIFIED = 0;
  FLIGHT_STATUS_SCHEDULED = 1;
  FLIGHT_STATUS_DELAYED = 2;
  FLIGHT_STATUS_CANCELLED = 3;
  FLIGHT_STATUS_DEPARTED = 4;
  FLIGHT_STATUS_COMPLETED = 5;
}

enum ReservationStatus {
  RESERVATION_STATUS_UNSPECIFIED = 0;
  RESERVATION_STATUS_ACTIVE = 1;
  RESERVATION_STATUS_RELEASED = 2;
  RESERVATION_STATUS_EXPIRED = 3;
}

message Flight {
  string id = 1;
  string flight_number = 2;

  string airline_code = 3;
  string airline_name = 4;

  string origin = 5;
  string destination = 6;

  google.protobuf.Timestamp departure_time = 7;
  google.protobuf.Timestamp arrival_time = 8;

  int32 total_seats = 9;
  int32 available_seats = 10;

  string price = 11;

  FlightStatus status = 12;

  google.protobuf.Timestamp created_at = 13;
  google.protobuf.Timestamp updated_at = 14;
}

message SeatReservation {
  string id = 1;
  string booking_id = 2;
  string flight_id = 3;
  int32 seats = 4;
  ReservationStatus status = 5;
  google.protobuf.Timestamp expires_at = 6;
  google.protobuf.Timestamp created_at = 7;
  google.protobuf.Timestamp updated_at = 8;
}

message SearchFlightsRequest {
  string origin = 1;
  string destination = 2;

  google.protobuf.Timestamp departure_from = 3;
  google.protobuf.Timestamp departure_to = 4;
}

message SearchFlightsResponse {
  repeated Flight flights = 1;
}

message GetFlightRequest {
  string flight_id = 1;
}

message GetFlightResponse {
  Flight flight = 1;
}

message ReserveSeatsRequest {
  string booking_id = 1;
  string flight_id = 2;
  int32 seat_count = 3;
  google.protobuf.Timestamp hold_until = 4;
}

message ReserveSeatsResponse {
  SeatReservation reservation = 1;
  int32 remaining_available_seats = 2;
}

message ReleaseReservationRequest {
  string booking_id = 1;
}

message ReleaseReservationResponse {
  SeatReservation reservation = 1;
  int32 released_seats = 2;
  int32 remaining_available_seats = 3;
}
